# Generated by Django 4.2.7 on 2023-12-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_book_period_book_category_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='poster/'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Author_davri', to='app.period'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_books', to='app.authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_books', to='app.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ganre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitob_ganri', to='app.ganre'),
        ),
    ]
